#!/usr/bin/env bash
# papers/wording/generate.sh                                       -*-sh-*-
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Regenerates the [expected] clause wording from the annotated headers in
# include/beman/expected/, via specgen (https://github.com/steve-downey/specgen).
#
# Produces:
#   papers/wording/fragments/*.tex  - one fragment per rSec2 clause, for
#                                      \input into a paper's own document.
#   papers/wording/expected.tex     - all fragments concatenated in real
#                                      standard clause order, wrapped in a
#                                      single \rSec1[expected]{Expected
#                                      objects}. This is the "wording only"
#                                      file: plain generated prose, with no
#                                      \input directives, suitable as the
#                                      basis for a diff against the actual
#                                      draft (github.com/cplusplus/draft)
#                                      source/utilities.tex.
#
# specgen must be on PATH. Run from anywhere; paths below are relative to
# this script's location.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$here/../.." && pwd)"
include_dir="$repo_root/include"
fragments_dir="$here/fragments"
work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT

mkdir -p "$fragments_dir"

gen() {
    local header="$1" outdir="$2"
    mkdir -p "$outdir"
    specgen generate "$include_dir/beman/expected/$header" \
        --backend latex --validate --no-compile-commands \
        --split "$outdir" \
        -- -std=c++2c -I "$include_dir"
}

echo "Generating from unexpected.hpp..." >&2
gen unexpected.hpp "$work_dir/unexpected"
echo "Generating from bad_expected_access.hpp..." >&2
gen bad_expected_access.hpp "$work_dir/bad"
echo "Generating from expected.hpp..." >&2
gen expected.hpp "$work_dir/expected"

# Map specgen's stable-name-derived filenames to the fragment names we keep.
cp "$work_dir/unexpected/expected.unexpected.tex" "$fragments_dir/unexpected.tex"
cp "$work_dir/bad/expected.bad.tex"               "$fragments_dir/bad.tex"
cp "$work_dir/bad/expected.bad.void.tex"          "$fragments_dir/bad-void.tex"
cp "$work_dir/expected/expected.expected.tex"     "$fragments_dir/object.tex"
cp "$work_dir/expected/expected.void.tex"         "$fragments_dir/void.tex"
cp "$work_dir/expected/expected.ref.tex"          "$fragments_dir/ref.tex"

# The generic per-header "root" fragments (named after the longest common
# stable-name prefix, e.g. expected.tex) hold exposition-only helper
# declarations (is_unexpected_specialization, reinit_expected,
# unexpect_dangles_v, converts_from_any_cvref) that live above any \rSec
# marker in the header. They are not part of the standard's own wording
# (the real draft states an equivalent helper, reinit-expected, inline in
# [expected.object.assign]'s own intro instead) and are intentionally
# omitted from the assembled clause below.

out="$here/expected.tex"
{
    echo '% papers/wording/expected.tex                                      -*-LaTeX-*-'
    echo '% SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception'
    echo '%'
    echo '% Generated by papers/wording/generate.sh from the annotated headers in'
    echo '% include/beman/expected/ via specgen. Do not edit by hand: re-run'
    echo '% generate.sh after changing a header'\''s //! docblocks instead.'
    echo '%'
    echo '% specgen numbers each fragment'\''s \rSec markers one level deeper than'
    echo '% written in the header ([expected.unexpected] etc. render as \rSec3, their'
    echo '% subclauses as \rSec4), matching the real standard'\''s absolute numbering'
    echo '% (22.8.3, 22.8.3.1, ...) directly. This file is therefore everything that'
    echo '% sits *inside* the existing \rSec2[expected]{Expected objects} in the'
    echo '% draft'\''s source/utilities.tex, in clause order, ready to replace the'
    echo '% current [expected.unexpected] through [expected.void] subclauses and add'
    echo '% the new [expected.ref] one after them -- no \rSec2[expected] wrapper and'
    echo '% no \input directives. [expected.general] and [expected.syn] are prose,'
    echo '% not generated from any one declaration; see papers/expected-new.tex.'
    echo
    for f in unexpected.tex bad.tex bad-void.tex object.tex void.tex ref.tex; do
        cat "$fragments_dir/$f"
        echo
    done
} > "$out"

echo "Wrote $out" >&2
echo "Wrote $fragments_dir/{unexpected,bad,bad-void,object,void,ref}.tex" >&2
